name: Initalize, format, plan and apply Iac

on: 
    push: 
        branches: 
            - main 
        paths: 
            - 'infra/**'
    workflow_dispatch: 

jobs: 
    infra_init-fmt-plan: 
        runs-on: ubuntu-latest

        defaults: 
         run: 
            working-directory: infra

        permissions: 
            id-token: write 
            contents: read 
            security-events: write
            actions: read
        
        steps: 
            - name: checkout code 
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner in IaC mode
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'config'
                scan-ref: 'infra'
                trivyignores: '.trivyignore'
                hide-progress: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                exit-code: '1'
                severity: 'CRITICAL,HIGH'
                limit-severities-for-sarif: true

            - name: Upload Trivy scan results to GitHub Security tab
              if: always()
              uses: github/codeql-action/upload-sarif@v4
              with:
                sarif_file: 'trivy-results.sarif'

            - name: configure AWS credentials 
              uses: aws-actions/configure-aws-credentials@v6.3.0
              with: 
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                role-session-name: infra_init-fmt-plan

            - name: install terraform 
              uses: hashicorp/setup-terraform@v4
              with: 
                terraform_version: 1.16.1

            - name: terraform format
              run: terraform fmt -check --recursive
            
            - name: terraform initalize
              run: terraform init

            - name: terraform validate 
              run: terraform validate

            - name: Set up TFLint
              uses: terraform-linters/setup-tflint@v6
              with: 
                tflint_version: v0.52.0
                cache: true

            - name: Show version
              run: tflint --version

            - name: Init TFLint
              run: tflint --init
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Run TFLint
              run: tflint -f compact --recursive

            - name: terraform plan
              run: terraform plan

    infra_apply:
        runs-on: ubuntu-latest
        needs: infra_init-fmt-plan
        environment: production
        
        defaults: 
         run: 
            working-directory: infra

        permissions: 
            id-token: write 
            contents: read 
            
        steps: 
          - name: checkout code 
            uses: actions/checkout@v4

          - name: configure AWS credentials 
            uses: aws-actions/configure-aws-credentials@v6.3.0
            with: 
              aws-region: ${{ secrets.AWS_REGION }}
              role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
              role-session-name: infra_apply

          - name: install terraform 
            uses: hashicorp/setup-terraform@v4
            with: 
              terraform_version: 1.16.1
            
          - name: terraform initalize
            run: terraform init

          - name: run terraform apply 
            run: terraform apply -auto-approve